### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by angeloashmore** [prismicio/prismic-types#14]
### Is your feature request related to a problem? Please describe.

The library currently does not contain tests. The types should be tested against known-good data shapes.

### Describe the solution you'd like

Create `.ts` files that are typed using the library's definitions. If the `.ts` files can be compiled with `tsc`, the tests pass.

For example, testing `SelectField` could look like this:

```ts
const filledSelectField1: prismicT.SelectField<"Option 1" | "Option 2", "filled"> = "Option 1"
const filledSelectField2: prismicT.SelectField<"Option 1" | "Option 2", "filled"> = "Option 2"
const emptySelectField: prismicT.SelectField<"Option 1" | "Option 2", "empty"> = null

// @ts-expect-error
const filledSelectField3: prismicT.SelectField<"Option 1" | "Option 2", "filled"> = "Option 3"
// @ts-expect-error
const filledSelectField4: prismicT.SelectField<"Option 1" | "Option 2", "filled"> = null
```

### Describe alternatives you've considered

None.

### Additional context

N/A

**Comment by lihbr** [comment]
That'd be great to have indeed! To me should go through a  `types` script, update the `test` one and add an extra step in the CI workflow.

I'm unsure in which folder those test files should live though 🤔

**Comment by angeloashmore** [comment]
Completed
