### ISSUE TITLE
 ImageField<ThumbnailNames> works with a single string literal, but not a union

### ISSUE THREAD

**Issue by benwest** [prismicio/prismic-types#27]
It looks to me like ImageField is supposed to accept multiple ThumbnailNames as a union, but that doesn't work. Am I using it wrong?

```ts
import * as prismicT from "@prismicio/types"

const img1: prismicT.ImageField<"small">
img1.small // fine

const img2: prismicT.ImageField<"small" | "medium">
img2.small // Property 'small' does not exist on type...
```

[Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5zFYqTAMYAqcAZlBCHAEQACm2uewEA9DAJ5gCmqlAsAFAC8EAHap4oAOYBGAFwYsOfAQB0ASRDJJnAGLBOAGwAmAHko5kBg5QB8cALxwA3gF8U6ZCLYCp0lRasBIVFxOCkAJnk6JUJ1TW09Q1NzTStKOAAfKhBOI2AAVxBbB2c3NBQvHxBJcP9UgyA)

**Comment by lihbr** [comment]
Hey there, thank you so much for the report!

You're doing everything right, so valid bug confirmed ✔️ We're working on fixing it in #29, should go out fairly soon if everything's alright :)
