### ISSUE TITLE
prismic.predicate.not type

### ISSUE THREAD

**Issue by LeoLfL** [prismicio/prismic-types#35]
### Versions

- @prismicio/types: 0.1.27
- @prismicio/client": "6.4.3",

### Reproduction

It looks like the types for prismic.predicate.not and for some others are incorrect. 

it's expected the single value 
<img width="801" alt="image" src="https://user-images.githubusercontent.com/22210892/169912778-a0bfcbf7-5faf-47b0-99ba-f82564c257e5.png">

but in this case prismic API return error :

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/22210892/169912828-081eb9c8-0f63-4681-aebd-2e946851c5b3.png">

and the correct one is using array : 

<img width="482" alt="image" src="https://user-images.githubusercontent.com/22210892/169912967-ea2581dc-2970-4b32-bfd7-3cd8bae1bb5f.png">

**Comment by lihbr** [comment]
Good catch! Looks like it's also an error within the documentation: https://prismic.io/docs/technologies/rest-api-technical-reference#not

The `not` predicate should work the same way as the `at` one, expecting a single value for all except `document.tags` where an array is desired.

PR is welcome to update the type on @prismicio/client: https://github.com/prismicio/prismic-client/blob/master/src/predicate.ts#L105-L111 ☺️

**Comment by angeloashmore** [comment]
Hey @LeoLfL, I just published @lihbr's fix ([see the PR here](https://github.com/prismicio/prismic-client/pull/241)) in `@prismicio/client@v6.5.0`.

Updating to the latest version should fix the TypeScript error:
```sh
npm i @prismicio/client@latest
```

Thanks for reporting the bug!
